version: 2
project_name: terraform-provider-goalert
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
  - formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - src: internal/client/operations.graphql
        dst: operations.graphql
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - '${signature}'
      - --detach-sign
      - '${artifact}'
release:
  draft: true
  prerelease: false
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
changelog:
  use: git
