query ProviderReadService($id: ID!) {
  service(id: $id) { id name description escalationPolicy { id } }
}
mutation ProviderCreateService($name: String!, $description: String!, $escalationPolicyID: ID!) {
  createService(input: {name: $name, description: $description, escalationPolicyID: $escalationPolicyID}) {
    id name description escalationPolicy { id }
  }
}
mutation ProviderUpdateService($id: ID!, $name: String!, $description: String!, $escalationPolicyID: ID!) {
  updateService(input: {id: $id, name: $name, description: $description, escalationPolicyID: $escalationPolicyID})
}
mutation ProviderDeleteService($id: ID!) {
  deleteAll(input: [{type: service, id: $id}])
}
query ProviderReadEscalationPolicy($id: ID!) {
  escalationPolicy(id: $id) {
    id
    name
    description
    repeat
    steps {
      id
      stepNumber
      delayMinutes
      actions {
        type
        args
      }
    }
  }
}
mutation ProviderCreateEscalationPolicy($input: CreateEscalationPolicyInput!) {
  createEscalationPolicy(input: $input) {
    id
    name
    description
    repeat
    steps {
      id
      stepNumber
      delayMinutes
      actions {
        type
        args
      }
    }
  }
}
mutation ProviderUpdateEscalationPolicy($input: UpdateEscalationPolicyInput!) {
  updateEscalationPolicy(input: $input)
}
mutation ProviderDeleteEscalationPolicy($id: ID!) {
  deleteAll(input: [{type: escalationPolicy, id: $id}])
}
mutation ProviderCreateEscalationPolicyStep($input: CreateEscalationPolicyStepInput!) {
  createEscalationPolicyStep(input: $input) {
    id
    stepNumber
    delayMinutes
    actions {
      type
      args
    }
  }
}
mutation ProviderUpdateEscalationPolicyStep($input: UpdateEscalationPolicyStepInput!) {
  updateEscalationPolicyStep(input: $input)
}
query ProviderReadIntegrationKey($id: ID!) {
  integrationKey(id: $id) {
    id
    name
    type
    href
    serviceID
  }
}
mutation ProviderCreateIntegrationKey($input: CreateIntegrationKeyInput!) {
  createIntegrationKey(input: $input) {
    id
    name
    type
    href
    serviceID
  }
}
mutation ProviderDeleteIntegrationKey($id: ID!) {
  deleteAll(input: [{type: integrationKey, id: $id}])
}
query ProviderReadHeartbeatMonitor($id: ID!) {
  heartbeatMonitor(id: $id) {
    id
    serviceID
    name
    timeoutMinutes
    href
  }
}
mutation ProviderCreateHeartbeatMonitor($input: CreateHeartbeatMonitorInput!) {
  createHeartbeatMonitor(input: $input) {
    id
    serviceID
    name
    timeoutMinutes
    href
  }
}
mutation ProviderUpdateHeartbeatMonitor($input: UpdateHeartbeatMonitorInput!) {
  updateHeartbeatMonitor(input: $input)
}
mutation ProviderDeleteHeartbeatMonitor($id: ID!) {
  deleteAll(input: [{type: heartbeatMonitor, id: $id}])
}
mutation ProviderSetServiceLabel($input: SetLabelInput!) {
  setLabel(input: $input)
}
query ProviderReadServiceLabels($id: ID!) {
  service(id: $id) {
    id
    labels {
      key
      value
    }
  }
}
query ProviderSearchServices($search: String!) {
  services(input: {search: $search, first: 15}) {
    nodes {
      id
      name
      description
      escalationPolicy { id }
    }
  }
}
query ProviderSearchEscalationPolicies($search: String!) {
  escalationPolicies(input: {search: $search, first: 15}) {
    nodes {
      id
      name
      description
      repeat
    }
  }
}
query ProviderReadUser($id: ID!) {
  user(id: $id) {
    id
    name
    email
    role
  }
}
mutation ProviderCreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    name
    email
    role
  }
}
mutation ProviderUpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input)
}
mutation ProviderDeleteUser($id: ID!) {
  deleteAll(input: [{type: user, id: $id}])
}
query ProviderSearchUsers($search: String!) {
  users(input: {search: $search, first: 15}) {
    nodes {
      id
      name
      email
      role
    }
  }
}
query ProviderReadUserContactMethod($id: ID!) {
  userContactMethod(id: $id) {
    id
    name
    disabled
    dest {
      type
      args
    }
  }
}
mutation ProviderCreateUserContactMethod($input: CreateUserContactMethodInput!) {
  createUserContactMethod(input: $input) {
    id
    name
    disabled
    dest {
      type
      args
    }
  }
}
mutation ProviderUpdateUserContactMethod($input: UpdateUserContactMethodInput!) {
  updateUserContactMethod(input: $input)
}
mutation ProviderDeleteUserContactMethod($id: ID!) {
  deleteAll(input: [{type: contactMethod, id: $id}])
}
query ProviderReadUserNotificationRules($userID: ID!) {
  user(id: $userID) {
    id
    notificationRules {
      id
      delayMinutes
      contactMethod {
        id
      }
    }
  }
}
mutation ProviderCreateUserNotificationRule($input: CreateUserNotificationRuleInput!) {
  createUserNotificationRule(input: $input) {
    id
    delayMinutes
    contactMethod {
      id
    }
  }
}
mutation ProviderDeleteUserNotificationRule($id: ID!) {
  deleteAll(input: [{type: notificationRule, id: $id}])
}
query ProviderReadRotation($id: ID!) {
  rotation(id: $id) {
    id
    name
    description
    type
    start
    timeZone
    shiftLength
    userIDs
    activeUserIndex
  }
}
query ProviderSearchRotations($search: String!) {
  rotations(input: {search: $search, first: 50}) {
    nodes {
      id
      name
      description
      type
      start
      timeZone
      shiftLength
      userIDs
      activeUserIndex
    }
  }
}
mutation ProviderCreateRotation($input: CreateRotationInput!) {
  createRotation(input: $input) {
    id
    name
    description
    type
    start
    timeZone
    shiftLength
    userIDs
    activeUserIndex
  }
}
mutation ProviderUpdateRotation($input: UpdateRotationInput!) {
  updateRotation(input: $input)
}
mutation ProviderDeleteRotation($id: ID!) {
  deleteAll(input: [{type: rotation, id: $id}])
}
